/**
 * AI-Powered Insights Generator
 *
 * Uses OpenAI GPT-4 to analyze repository README and generate:
 * - Project purpose
 * - Technology stack
 * - Notable features
 * - Improvement suggestions
 * - Common mistakes identified
 */

import OpenAI from 'openai'
import { GitHubClient } from '@/services/integrations/github-client'

/**
 * Repository insights generated by AI
 */
export interface RepositoryInsights {
  purpose: string
  techStack: string[]
  features: string[]
  improvements: string[]
  mistakes: string[]
}

/**
 * Insights Generator configuration
 */
interface InsightsGeneratorConfig {
  model?: string
  temperature?: number
  maxTokens?: number
}

/**
 * Insights Generator
 * Uses OpenAI to analyze repository README and generate insights
 */
export class InsightsGenerator {
  private openai: OpenAI
  private model: string
  private temperature: number
  private maxTokens: number

  constructor(
    private githubClient: GitHubClient,
    config: InsightsGeneratorConfig = {}
  ) {
    const apiKey = process.env.OPENAI_API_KEY

    if (!apiKey) {
      throw new Error('OPENAI_API_KEY environment variable is required')
    }

    this.openai = new OpenAI({ apiKey })
    this.model = config.model || 'gpt-4o-mini' // Use GPT-4o-mini for cost efficiency
    this.temperature = config.temperature || 0.7
    this.maxTokens = config.maxTokens || 2000
  }

  /**
   * Generate insights for a repository
   *
   * @param owner - Repository owner
   * @param repo - Repository name
   * @param description - Repository description from GitHub
   * @returns AI-generated insights
   */
  async generateInsights(
    owner: string,
    repo: string,
    description: string | null
  ): Promise<RepositoryInsights> {
    try {
      // Fetch README content
      const readmeContent = await this.fetchReadme(owner, repo)

      if (!readmeContent) {
        // If no README, return minimal insights based on description
        return this.generateMinimalInsights(description)
      }

      // Generate insights using OpenAI
      const insights = await this.analyzeWithAI(readmeContent, description, repo)

      return insights
    } catch (error) {
      console.error('Insights generation failed:', error)
      // Return minimal insights on error
      return this.generateMinimalInsights(description)
    }
  }

  /**
   * Fetch README content from repository
   * @private
   */
  private async fetchReadme(owner: string, repo: string): Promise<string | null> {
    const readmeFiles = ['README.md', 'readme.md', 'README', 'readme']

    for (const filename of readmeFiles) {
      try {
        const content = await this.githubClient.getFileContent(owner, repo, filename)
        return content
      } catch {
        continue
      }
    }

    return null
  }

  /**
   * Analyze repository with OpenAI
   * @private
   */
  private async analyzeWithAI(
    readmeContent: string,
    description: string | null,
    repoName: string
  ): Promise<RepositoryInsights> {
    // Truncate README if too long (max 4000 chars to stay within token limits)
    const truncatedReadme =
      readmeContent.length > 4000
        ? readmeContent.substring(0, 4000) + '...[truncated]'
        : readmeContent

    const prompt = this.buildAnalysisPrompt(truncatedReadme, description, repoName)

    try {
      const response = await this.openai.chat.completions.create({
        model: this.model,
        messages: [
          {
            role: 'system',
            content:
              'You are an expert software engineer analyzing GitHub repositories. Provide concise, actionable insights in valid JSON format.',
          },
          {
            role: 'user',
            content: prompt,
          },
        ],
        temperature: this.temperature,
        max_tokens: this.maxTokens,
        response_format: { type: 'json_object' },
      })

      const content = response.choices[0]?.message?.content

      if (!content) {
        throw new Error('No response from OpenAI')
      }

      // Parse JSON response
      const parsed = JSON.parse(content)

      return {
        purpose: parsed.purpose || 'Unknown purpose',
        techStack: Array.isArray(parsed.techStack) ? parsed.techStack : [],
        features: Array.isArray(parsed.features) ? parsed.features : [],
        improvements: Array.isArray(parsed.improvements) ? parsed.improvements : [],
        mistakes: Array.isArray(parsed.mistakes) ? parsed.mistakes : [],
      }
    } catch (error) {
      console.error('OpenAI analysis failed:', error)
      throw error
    }
  }

  /**
   * Build analysis prompt for OpenAI
   * @private
   */
  private buildAnalysisPrompt(
    readme: string,
    description: string | null,
    repoName: string
  ): string {
    return `Analyze this GitHub repository and provide insights in JSON format.

Repository: ${repoName}
${description ? `Description: ${description}` : ''}

README Content:
${readme}

Please analyze the repository and provide:

1. **purpose**: A single concise sentence (max 100 chars) explaining what this project does
2. **techStack**: Array of main technologies/frameworks used (max 10 items, be specific)
3. **features**: Array of 3-5 notable features or capabilities
4. **improvements**: Array of 3-5 specific suggestions for improvement (focus on code quality, documentation, testing, architecture)
5. **mistakes**: Array of 2-4 common mistakes or anti-patterns identified (be constructive)

Return ONLY valid JSON in this exact format:
{
  "purpose": "string",
  "techStack": ["string"],
  "features": ["string"],
  "improvements": ["string"],
  "mistakes": ["string"]
}

Be specific, actionable, and constructive. Focus on what you can determine from the README.`
  }

  /**
   * Generate minimal insights when README is not available
   * @private
   */
  private generateMinimalInsights(
    description: string | null
  ): RepositoryInsights {
    return {
      purpose: description || 'No description available',
      techStack: [],
      features: [],
      improvements: [
        'Add a comprehensive README with project description',
        'Include setup instructions and dependencies',
        'Add usage examples and documentation',
      ],
      mistakes: ['Missing README file - critical for project discoverability'],
    }
  }
}

/**
 * Create insights generator instance
 *
 * @param githubClient - GitHub client instance
 * @param config - Optional configuration
 * @returns InsightsGenerator instance
 */
export function createInsightsGenerator(
  githubClient: GitHubClient,
  config?: InsightsGeneratorConfig
): InsightsGenerator {
  return new InsightsGenerator(githubClient, config)
}
